title: Reckless Slowpoke Wisdom
author: Reckless Slowpoke
description: > # this means to ignore newlines until "baseurl:"
  This is a small site to hold all the wisdom that Reckless Slowpoke can 
  provide to this World.

# social links
github_username:  reckless-slowpoke

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
